### ISSUE TITLE
Combine command doesn't update existing string, just adds or remove string

### ISSUE THREAD

**Issue by nebojsazr** [AlexDaSoul/ngx-i18n-combine#1]
I have file i18n/common/en.json  and  i18n/en.json
And string `"something": "something translated"`  inside both of them

In i18n/common/en.json I changed to `"something": "translated even better"` and run command

`ngx-i18n-combine -i ./src/assets/i18n/** -o ./src/assets/i18n/{en,de,fr}.json`

In file i18n/en.json  nothing is changed 

Works if I add new string, but not when changing existing

Edit: Also that adding/removing strings works just for first level json props, not for nested

**Comment by AlexDaSoul** [comment]
ngx-i18n-combine -i ./src/assets/i18n/** -o ./src/assets/i18n/{en,de,fr}.json

Are you looking for files in the assets folder?

ngx-i18n-combine -i ./src/common/i18n/** -o ./src/assets/i18n/{en,de,fr}.json

**Comment by nebojsazr** [comment]
> ngx-i18n-combine -i ./src/common/i18n/** -o ./src/assets/i18n/{en,de,fr}.json

No, that's completely wrong (ERROR: files not found). Full path is ./src/assets/i18n/common  for particular source folder, and I have many more.

If path was the problem then it would not work at all, but it works when adding/removing strings in first level json structure

**Comment by AlexDaSoul** [comment]
Try ./src/assets/i18n/**/*

**Comment by nebojsazr** [comment]
> Try ./src/assets/i18n/**/*

Yeah work that way. Thank you very much for quick responding.
